# ---- NAMESPACE ---- #

apiVersion: v1
kind: Namespace
metadata:
  name: 
  labels:
    name: 
    app: 


---


# ---- SERVICEACCOUNT ---- #

apiVersion: v1
kind: ServiceAccount
metadata:
  name: 
  namespace: 


---


# ---- CLUSTER ROLE BINDING ---- #

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: 
  labels:
    app: 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: 
  namespace: 


---


# ---- DEPLOYMENT ---- #

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 
  name: 
  labels:
    app: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      serviceAccountName: default
      containers:
      - name: 
        image: 
        ports:
        - name: 
          containerPort: 
        env:
        - name:
          value: 
        volumeMounts:
        - name: 
          mountPath: 
      volumes:
      - name: 
        configMap:
          name: 


---


# ---- SERVICE ---- #

apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: 
  labels:
    app: 
spec:
  type: ClusterIP
  selector:
    app: 
  ports:
  - name: 
    port: 
    targetPort: 


---


# ---- INGRESS ---- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 
  namespace: 
  labels:
    app: 
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /
        backend:
          serviceName: 
          servicePort: 


---


# ---- CONFIGMAP ---- #

apiVersion: v1
kind: ConfigMap
metadata:
  name: 
  namespace: 
data:
  a.file: |
    data