kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: springboot-demo-pvc1
  labels:
    app: springboot-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: network-share
