apiVersion: v1
kind: PersistentVolume
metadata:
  name: springboot-demo-$environment
  labels:
    app: springboot-demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: network-share
  nfs:
    path: /a/path
    server: a.server.address
