apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-demo-$environment
  namespace: $namespace
data:
  app.properties: |
    environment=$environment
  telegraf.conf:  |
    [[inputs.http_response]]
      address = "http://localhost"
      response_timeout = "2s"
      method = "GET"
    [[outputs.prometheus_client]]
      listen = ":9273"
      path = "/metrics"
      expiration_interval = "60s"
  