apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prometheus
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      serviceAccountName: default
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:latest
        #command: [""]
        #args: [""] 
        ports:
        - name: http
          containerPort: 9115
