kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc1
  namespace: prometheus
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: network-share
