# ---------- Namespace ---------- #

apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    name: grafana
    app: grafana

---

# ---------- Deployment ---------- #

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grafana
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:5.2.2
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - name: appdata
              mountPath: /var/lib/grafana/        
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: grafana-pvc1

---

# ---------- Persistent Volume ---------- #

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: network-share
  nfs:
    path:   /volume1/kubernetes_volumes/grafana
    server: nas.schuldt.lcl

---

# ---------- Persistent Volume Claim ---------- #

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc1
  namespace: grafana
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: network-share

---

# ---------- Service ---------- #

kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http
      port: 80
      targetPort: http

---

# ---------- Ingress ---------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  rules:
    - host: grafana.schuldt.lcl
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: http
