apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-demo-$environment
  labels:
    app: nodejs-demo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: network-share
  nfs:
    path: /a/path/
    server: a.server.address
