kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nodejs-demo-pvc1
  labels:
    app: nodejs-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: network-share
