kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dnsutils-pvc1
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
