kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 
subjects:
  - kind: ServiceAccount
    name: 
    namespace: default
roleRef:
  kind: ClusterRole
  name: 
  apiGroup: rbac.authorization.k8s.io



---



kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 
subjects:
  - kind: ServiceAccount
    name: 
    namespace: default
roleRef:
  kind: Role
  name: 
  apiGroup: rbac.authorization.k8s.io