apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: 
  namespace:
  labels:
    app:  
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: 
            image: 
            command: [""]
            args: [""]
          restartPolicy: OnFailure