- hosts: localhost
  connection: local
  tasks:
    - name: apply stack
      shell: "envsubst < {{item}}.yml |kubectl apply -f -"
      loop:
        - namespaces
        - deployment
        - service_clusterip
        - ingress